### ISSUE TITLE
Missing outputs

### ISSUE THREAD

**Issue by BioFalcon** [metaphysicser/HAlign-4#1]
Hi,

I'm trying to use halign4, but I don't get an output but there are no error messages or non-zero exit codes generated.

Could you look into it? This is the softwares output message:
```
[  Input_name  ] : TEST.fa

[  Output_name ] : TEMP.aln

[   Reference  ] = [Longest]

[    Threads   ] = 8

[      SA      ] = 15

2024-11-29 11:47:48 | Start: Read and data preprocessing: 1 files
                    | Info : read consumes : 1ms

2024-11-29 11:47:48 | End  : 325 sequences were discovered

2024-11-29 11:47:48 | Start: build Suffix Array No.175

2024-11-29 11:47:48 | End  : build Suffix Array 1ms

2024-11-29 11:47:48 | Start: pairwise sequence alignment

2024-11-29 11:47:48 | End  : pairwise sequence alignment

| Info : align time consumes : 135ms

| Info : align memory peak   : 67735552 B

| Info : write consumes: 0ms

| Info : Current pid   : 11904

| Info : Time consumes : 139ms

| Info : Memory usage  : 67735552 B
```

Cheers,
F

**Comment by metaphysicser** [comment]
@BioFalcon 
Thank you for raising this issue. We have identified the cause of the problem, and as a temporary workaround, you can change the file name TEST.aln to TEMP.fasta to obtain the desired results. We sincerely apologize for the inconvenience caused. We will update the code to resolve this issue as soon as possible.

**Comment by pinglu-zhang** [comment]
@BioFalcon 
Thank you for raising this issue. We have identified the cause of the problem, and as a temporary workaround, you can change the file name TEMP.aln to TEMP.fasta to obtain the desired results. We sincerely apologize for the inconvenience caused. We will update the code to resolve this issue as soon as possible.

**Comment by BioFalcon** [comment]
Can confirm this fixes this. Thanks a lot!
